default: &default
  port: 3100
  token: ENV['GH_TOKEN']
  base_url: ""
  org_name: ""
  event_endpoint: ""
  user_endpoint: ""
  refresh_seconds: 300

development:
  <<: *default
  base_url: "https://repos.wyzdev.com/api/v3"
  event_endpoint: "/repos/wyzant-web/%v/events"
  user_endpoint: "/users/%v"
  name: "Mike"
  refresh_seconds: 30