default: &default
  port: 3100
  token: ""
  base_url_template: ""
  org_name: ""
  repo_host: ""
  event_endpoint: ""
  user_endpoint: ""
  refresh_seconds: 300
  repo_to_watch: ""
  log_level: "info"

development:
  <<: *default
  token: ""
  base_url_template: ""
  org_name: ""
  repo_host: ""
  event_endpoint: ""
  user_endpoint: ""
  refresh_seconds: 30
  repo_to_watch: ""
  log_level: "info"
  